### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by wudi00** [amdegroot/ssd.pytorch#447]
The following errors were encountered in training.
PyTorch 1.2.0
python 3.6
`Traceback (most recent call last):
  File "train.py", line 257, in <module>
    train()
  File "train.py", line 97, in train
    ssd_net = build_ssd('train', cfg['min_dim'], cfg['num_classes'])
  File "/media/disk/wudi/ssd.pytorch/ssd.py", line 207, in build_ssd
    base_, extras_, head_ = multibox(vgg(base[str(size)], 3),
  File "/media/disk/wudi/ssd.pytorch/ssd.py", line 136, in vgg
    conv2d = nn.Conv2d(in_channels, v, kernel_size=3, padding=1)
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 330, in __init__
    False, _pair(0), groups, bias, padding_mode)
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 41, in __init__
    out_channels, in_channels // groups, *kernel_size))
RuntimeError: CUDA error: out of memory
`
What is the reason for this mistake? Thanks.

**Comment by Songtingt** [comment]
maybe you can use this command to check your gpu usage condition : nvidia-smi
Then add this thing in front of your code to use the free graphics card :
CUDA_VISIBLE_DEVICES="6" python train.py  (6 is just an example)

**Comment by wudi00** [comment]
OK, I use that command, and it works. Thanks!

**Comment by Songtingt** [comment]
> OK, I use that command, and it works. Thanks!

you're welcome :smile:
